### ISSUE TITLE
[EPIC] Vector cube: merging & filtering

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#771]
Users want to use large geoparquet files as input data for model training. 
To make this efficient, this requires a few extra features:

- [ ] combining multiple vector cubes with merge_cubes
- [ ] loading only specific columns of vector cube, reducing size
- [ ] filtering vector cubes (at load time) on spatial extent
- [ ] filtering vector cubes (at load time) on properties

For timing, we'll want this in 3-4 months.

Design wise, ideally we can convert openEO process graph into SQL statement that can be used by DuckDB or SparkSQL.
